#!/bin/bash

for GENOME in `cat inputs-sample.txt`; do
    FOUND=0
    for READ in `seq 1 10`; do
        if ils /iplant/home/shared/irri/read$READ/T11073/Fq/$GENOME >/dev/null 2>&1; then
            for F in `ils /iplant/home/shared/irri/read$READ/T11073/Fq/$GENOME/ | grep -v -E "^\/"`; do
                echo "irods:///iplant/home/shared/irri/read$READ/T11073/Fq/$GENOME/$F"
            done
            FOUND=1
            break
        fi
    done
    if [ $FOUND = 0 ]; then
        echo "$GENOME not found!"
    else
        echo "$GENOME added."
    fi
done

